name: TypeScript CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-run-and-archive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Compile TypeScript
      run: npx tsc

    - name: Run script and capture output
      # This command runs the script and redirects both stdout (>) and stderr (2>&1)
      # into a file named 'output.log'. The '|| true' ensures the workflow continues
      # even if the script fails, allowing the log to be uploaded regardless.
      run: node dist/ultra_proper_proof.js > output.log 2>&1 || true

    - name: Upload run log
      # This action takes the generated log file and uploads it as a workflow artifact.
      uses: actions/upload-artifact@v4
      with:
        name: run-log # The name of the artifact bundle.
        path: output.log # The path to the file to upload.

